project:
  type: website

website:
  title: "Ozan Ozbeker"
  description: "The professional website of Ozan Ozbeker."
  favicon: resources/images/coding.ico
  site-url: https://ozanozbeker.github.io
  repo-url: https://github.com/ozanozbeker/ozanozbeker.github.io
  navbar:
    left:
      - href: index.qmd
        text: About
        icon: file-person
      - href: resume.qmd
        text: Resume/CV
        icon: file-earmark-text
      - href: blog.qmd
        text: Blog
        icon: journal-code
    tools:
      - icon: github
        href: https://github.com/ozanozbeker/
      - icon: linkedin
        href: https://www.linkedin.com/in/ozanozbeker/
      - icon: envelope
        href: mailto:ozanozbeker99@outlook.com
  page-navigation: true
  page-footer:
    left: "Copyright 2024, Ozan Ozbeker"
    right: "This website was made by me and powered by Quarto!"
  twitter-card: true
  open-graph: true

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual
