project:
  type: website

website:
  title: "Ozan Ozbeker"
  navbar:
    left:
      - href: index.qmd
        text: About Me

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

