project:
  type: website
  render:
    - index.qmd
    - resume.qmd
    - blog.qmd
    - blog/*.qmd
    - 404.qmd
  preview:
    port: 4200
    browser: true
  resources: resources

execute:
  freeze: auto

website:
  title: "Ozan Ozbeker"
  description: "The professional website of Ozan Ozbeker."
  favicon: resources/icons/code.svg
  site-url: https://ozanozbeker.io
  repo-url: https://github.com/ozanozbeker/ozanozbeker.io
  navbar:
    logo: resources/icons/code.svg
    search: false
    left:
      - href: resume.qmd
        text: "Resume"
      - href: blog.qmd
        text: "Blog"
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: "Copyright 2024, Ozan Ozbeker"
    right: "This website was made by me and powered by [Quarto](https://www.quarto.com)!"
  open-graph: true

format:
  html:
    theme:
      light: [flatly, resources/themes/flatly-nord-ozbeker.scss]
      dark:  [darkly, resources/themes/darkly-nord-ozbeker.scss]

editor: visual
