project:
  type: website
  render:
    - index.qmd
    - resume.qmd
    - blog.qmd
    - blog/*.qmd
  preview:
    port: 4200
    browser: true
  resources: resources

execute:
  freeze: auto

website:
  title: "Ozan Ozbeker"
  description: "The professional website of Ozan Ozbeker."
  favicon: resources/images/web-development.ico
  site-url: https://ozanozbeker.github.io
  repo-url: https://github.com/ozanozbeker/ozanozbeker.github.io
  navbar:
    right:
      - href: resume.qmd
        text: "Resume"
      #  icon: file-earmark-text
      - href: blog.qmd
        text: "Blog"
      #  icon: journal-code
  page-navigation: true
  page-footer:
    left: "Copyright 2024, Ozan Ozbeker"
    right: "This website was made by me and powered by Quarto!"
  open-graph: true

format:
  html:
    theme: [simplex, simplex_ozbeker.scss]

editor: visual
