project:
  type: website
  preview:
    port: 4200
    browser: true
  resources: resources

execute:
  freeze: auto

website:
  title: "Ozan Ozbeker"
  description: "The professional website of Ozan Ozbeker."
  favicon: resources/images/favicon.ico
  site-url: https://ozanozbeker.github.io
  repo-url: https://github.com/ozanozbeker/ozanozbeker.github.io
  navbar:
    left:
      - href: resume.qmd
        text: "Resume"
        icon: file-earmark-text
      - href: blog.qmd
        text: "Blog"
        icon: journal-code
    tools:
      - icon: github
        href: https://github.com/ozanozbeker/
      - icon: linkedin
        href: https://www.linkedin.com/in/ozanozbeker/
      - icon: envelope
        href: mailto:ozanozbeker99@outlook.com
  page-navigation: true
  page-footer:
    left: "Copyright 2024, Ozan Ozbeker"
    right: "This website was made by me and powered by Quarto!"
  open-graph: true

format:
  html:
    theme:
      - simplex
      - custom.scss

editor: visual
